### ISSUE TITLE
[BUG]Can't synchronize, can you give me some nodes?

### ISSUE THREAD

**Issue by 1617176084** [ChandlerFerry/deafwave-blockchain#14]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by ChandlerFerry** [comment]
Hello,

We are currently on testnet. If you are still experiencing issues with synchronizing after I released DNS Seeders on testnet yesterday, please reopen this ticket with some information about what you are experiencing.
