### ISSUE TITLE
[BUG] Can't stop all services running via deafwave stop all on fix/dns branch

### ISSUE THREAD

**Issue by ZeDon-SP** [ChandlerFerry/deafwave-blockchain#18]
**Describe the bug**
The command 'deafwave stop all' on branch fix/dns [as of time of opening this report] doesn't compute correctly the actions to perform.

**To Reproduce**
deafwave start farmer && deafwave stop all

**Expected behavior**
All services are stopped gracefully

**Desktop (please complete the following information):**

- OS: Debian Buster

**Additional context**
/deafwave-blockchain$ deafwave stop all
deafwave_harvesterdeafwave_timelord_launcherdeafwave_timelorddeafwave_farmerdeafwave_full_nodedeafwave_wallet: Not running

**Comment by ChandlerFerry** [comment]
Ah yeah, I probably broke this. I'll go ahead and take a look. Thanks!

**Comment by ChandlerFerry** [comment]
Resolved, please validate.
